// src/BattlEyeManager.Spa/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { Router } from '@angular/router';

import {AuthService} from '../auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  form: FormGroup;

  constructor(private fb: FormBuilder,
    private authService: AuthService,
    private router: Router) {
      this.form = this.fb.group({
        email: ['', Validators.required],
        password: ['', Validators.required]
      });
    }

  login() {
    const val = this.form.value;
    if (val.email && val.password) {
      this.authService.login(val.email, val.password)
        .then(() => this.router.navigate(['/']));
    }
  }

}

<div class="text-center body">
  <form class="form-signin" #form="ngForm" novalidate (ngSubmit)="submit(form)">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

    <div class="form-group">
      <input type="text" class="form-control" #email="ngModel" name="email" [(ngModel)]="user.email" placeholder="User Name" required autofocus>
    </div>

    <div class="form-group">
      <input type="password" class="form-control" #password="ngModel" name="password" [(ngModel)]="user.password" placeholder="Password" required>
    </div>

    <button class="btn btn-lg btn-primary btn-block">Sign in</button>
    <hr />
    <footer>
      <p>&copy; 2018 - BattlEye Manager</p>
    </footer>
  </form>
</div>

// src/BattlEyeManager.React/src/pages/login/login.js
import React, { Component } from 'react';
import './login.css'

export class Login extends Component {

  render() {
    const { handleSubmit } = this.props;

    return (
      <div className="text-center body">
        <form className="form-signin" >
          <h1 className="h3 mb-3 font-weight-normal">Please sign in</h1>
          <div className="form-group">
            <input type="text" className="form-control" name="email" placeholder="User Name" required autofocus />
          </div>

          <div className="form-group">
            <input type="password" className="form-control" name="password" placeholder="Password" required />
          </div>

          <button className="btn btn-lg btn-primary btn-block">Sign in</button>
          <hr />
          <footer>
            <p>&copy; 2018 - BattlEye Manager</p>
          </footer>
        </form>
      </div>);
  }
}
